import Vue from 'vue';
import { Button, Search, Swipe, SwipeItem, Icon, Tag, DropdownMenu, DropdownItem, Empty, List, Cell, CellGroup, Toast, Tabbar, TabbarItem, Dialog, Form, Field, Image as VanImage, Lazyload,Col,Row, Popup,Sku,GoodsAction, GoodsActionIcon, GoodsActionButton } from 'vant';

Vue.use(Button);
Vue.use(Search);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Icon);
Vue.use(Tag);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Empty);
Vue.use(List);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Form);
Vue.use(Field);
Vue.use(Dialog);
Vue.use(VanImage);
Vue.use(Lazyload); 
Vue.use(Col);
Vue.use(Row);
Vue.use(Popup);
Vue.use(Sku);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);